services:
  # PostgreSQL Database
  - type: pserv
    name: gift-app-db
    env: docker
    plan: free
    region: frankfurt

  # Backend API
  - type: web
    name: gift-app-api
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma migrate deploy && node dist/main.js
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: gift-app-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
